<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="mcadmins-MacBook-Pro-2.local" failures="2" tests="4" name="NetBanking" time="17.732" errors="0" timestamp="2023-06-09T17:35:01 EDT">
  <testcase classname="com.qa.testCases.LoginTest" name="logintest" time="1.43"/>
  <testcase classname="com.qa.testCases.LoginTest_DataDriven" name="logintest" time="1.983"/>
  <testcase classname="com.qa.testCases.LoginTest_DataDriven" name="logintest" time="0.957">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.testCases.LoginTest_DataDriven.logintest(LoginTest_DataDriven.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
  <testcase classname="com.qa.testCases.LoginTest_DataDriven" name="logintest" time="1.332">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.testCases.LoginTest_DataDriven.logintest(LoginTest_DataDriven.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
</testsuite> <!-- NetBanking -->
